services:
  face-recognition:
    build: .
    container_name: face_recognition_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./dataset:/app/dataset
      - ./embeddings:/app/embeddings
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - DATABASE_URL=${FACE_DB_URL}

  golang-service:
    build:
      context: ../golang-project  # Adjust this path to your Golang project
      dockerfile: Dockerfile
    container_name: golang_api
    restart: always
    ports:
      - "8080:8080"  # Adjust port as needed for your Golang app
    env_file:
      - .env
    environment:
      - DATABASE_URL=${GO_DB_URL}
      - FACE_API_URL=http://face-recognition:5000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: combined_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/combined.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - face-recognition
      - golang-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
