version: "3.8"

services:
  web:
    build: .
    container_name: face_api
    restart: always
    volumes:
      - ./dataset:/app/dataset
      - ./embeddings:/app/embeddings
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: face_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
